### ISSUE TITLE
Slow initial loading

### ISSUE THREAD

**Issue by knownasilya** [locks/tombot-viewer#3]
I think this has something to do with the ajax request.. really unsure, but it's really bad.

**Comment by locks** [comment]
@knownasilya confirm. It's spinning up an AWS Lambda, which then makes a request to the Redis database.
Hm, I wouldn't mind caching on a couchdb and then replication to a pouchdb like the guides and the api viewers. Otherwise, we would need to replace the Lambda with a proxy server, but I'm a cheapskate :P

**Comment by knownasilya** [comment]
Maybe we could use https://zeit.co/now#

**Comment by knownasilya** [comment]
How do I access the redis server?

**Comment by locks** [comment]
DMed the details.
